http:
  middlewares:
    secured-hsts:
      chain:
        middlewares:
        - default-headers
        - default-hsts-headers

    https-redirect:
      redirectScheme:
        scheme: https
        permanent: true

    default-headers:
      headers:
        frameDeny: true
        browserXssFilter: true
        contentTypeNosniff: true
        referrerPolicy: "no-referrer"

    default-hsts-headers:
      headers:
        forceSTSHeader: true
        stsPreload: true
        stsSeconds: 63072000
        stsIncludeSubdomains: true
