api:
  dashboard: true
  insecure: false

entryPoints:
  web:
    address: :80
  web-secure:
    address: :443
  ipfs-tcp:
    address: ":4001/tcp"
  ipfs-udp:
    address: ":4001/udp"
  matrix:
    address: :8448
  kipa:
    address: :10842

providers:
  docker:
    endpoint: unix:///var/run/docker.sock
    exposedByDefault: false
  file:
    directory: /rules
    watch: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: webmaster@chrislane.com
      storage: acme.json
      dnsChallenge:
        provider: cloudflare
